# Generated by Django 4.2.5 on 2023-09-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-yzA7KgVUD7C_hwJnrlfxCISOHOWjpSuTm4bCfJSkhKmfnT8EUOEXtKyCOEro1ncuxS0&usqp=CAU', max_length=500),
        ),
    ]
